### ISSUE TITLE
Java SDK instructions are missing

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-linode#389]
### What happened?

This package is missing the instructions for Java SDK installation, both in the README here and in the [Install and Config page in the Pulumi Registry](https://www.pulumi.com/registry/packages/linode/installation-configuration/).

### Example

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
Suggest doing an audit of all of our packages, since it's likely others have the same issue. This issue came to me via someone in the Pulumi Community Slack who assumed no Java SDK existed.

**Comment by mikhailshilkov** [comment]
I added links to install pages for all packages in https://github.com/pulumi/registry/pull/3568

None of our providers mention how to install Java SDKs in their READMEs... I had a quick look and found no obvious command to include there, actually. I'll resolve this issue as fixed, since linode and other small packages are now on-par with the "big guys". If we want to improve READMEs, let's open a separate enhancement (maybe in /home).
