### ISSUE TITLE
`InstanceConfig` Resource Mentioned in Docs Does Not Exist

### ISSUE THREAD

**Issue by zicklag** [pulumi/pulumi-linode#744]
I'm trying to use the TypeScript version of this library and I've found that the `configs` option on `Instance` is deprecated, and from the docs [here](https://www.pulumi.com/registry/packages/linode/api-docs/instance/#linode-instance-with-explicit-configs-and-disks) it appears that I'm supposed to alternatively use an `InstanceConfig` resource like this:

```ts
const bootConfig = new linode.index.InstanceConfig("boot_config", {
    label: "boot_config",
    linodeId: web.id,
    devices: [
        {
            deviceName: "sda",
            diskId: bootDisk.id,
        },
        {
            deviceName: "sdb",
            volumeId: webVolume.id,
        },
    ],
    rootDevice: "/dev/sda",
    kernel: "linode/latest-64bit",
    booted: true,
});
```

However, the `InstanceConfig` resource doesn't exist in the documentation, nor am I able to find it in the TypeScript library. Guidance would be appreciated.

**Comment by guineveresaenger** [comment]
Hi @zicklag - thank you for filing this issue and alerting us to the doscrepancy!

You are correct that this instance is [not mapped in the provider](https://github.com/pulumi/pulumi-linode/blob/master/provider/resources.go#L141), and apparently this was done deliberately.

My best guess is that in the past there was a naming conflict that has since resolved. I will confer with the team and see if the need for this override still applies or not.

**Comment by zicklag** [comment]
Thank you! 🎉
